apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erigon-helm-remote
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://github.com/denis-safedev/argocd-remote
    targetRevision: HEAD
    path: "./"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true